### ISSUE TITLE
Missing dependency pyqt

### ISSUE THREAD

**Issue by gdolle** [cbrnr/mnelab#182]
It seems `pyqt5` package is missing in requirement.txt ?

To reproduce:

```bash
virtualenv mnelab_venv
source ./mnelab_venv/bin/activate
pip install -r requirement.txt
pip install -r requirement-extras.txt
# pip install pyqt5
python setup.py build
python setup.py install
./mnelab_venv/bin/mnelab
```

PS: I saw the readme mention it, but why not set either pyqt5 or pyside2 in requirement ?

**Comment by cbrnr** [comment]
MNELAB requires `qtpy`, which is a wrapper for either `PyQt5` or `PySide2`. I don't think there is a way to specify this dependency (meaning either `PyQt5` *or* `PySide2`) in `requirements.txt`. However, I do mention this in `README.md`, and the error message does indicate that `qtpy.PythonQtError: No Qt bindings could be found` &ndash; meaning it doesn't tell you that `PyQt5` is missing because you are free to use whatever Qt bindings that are supported.

Do you have an idea how to make this clearer? I don't think we can solve this in code, and I don't want to add *both* `PyQt5` and `PySide2` as dependencies. Maybe the `pyqt` error message could be more specific? This might be worth reporting upstream.

**Comment by gdolle** [comment]
Ok I see the issue.

Indeed it "seems" setuptools does not handle underlying wrapped packages (requirement.txt for sure) ... 

Below, I propose a workaround for a "setup.py" that use "install_requires"

```py
from importlib import import_module
from setuptools import setup

def optdep(deps,default=None):
    if(len(deps)):
        try:
            dep = deps.pop(0)
            import_module(dep)
            print("Wrapped package used: ",dep)
        except ImportError:
            optdep(deps,default)
        return dep 
    else:
        print("Wrapped package will use by default: ", default)
        return default

setup(name='Example',
      version='1.0',
      description='Example',
      author='test',
      author_email='email@email.com',
      url='myurl',
      install_requires=optdep(["PySide2", "PyQt5"],"PySide2")
     ) 
```
This `optdep(["PySide2", "PyQt5"],"PySide2") ` function try to import modules from the given package ordered list. If can't, the given default one is returned.
The only drawback iI see is you have to respect the letter case (PySide2 not pyside2) and then set all wrapped packages...


you can try like this:

```sh
# Test1
virtualenv test1_venv
source ./test1_venv/bin/activate
python setup.py install

# Test2
virtualenv test2_venv
source ./test2_venv/bin/activate
pip install pyqt5 # assume already installed
python setup.py install
```

**Comment by cbrnr** [comment]
Nice workaround! Let's use a non-recursive version though, i.e.

```python
def optdep(deps, default=None):
    for dep in deps:
        try:
            import_module(dep)
        except ImportError:
            continue
        else:
            return dep
    return default
```

WDYT?

**Comment by gdolle** [comment]
Ok for me :+1:

**Comment by cbrnr** [comment]
@gdolle do you want to prepare a PR?

**Comment by gdolle** [comment]
@cbrnr PR #187
