### ISSUE TITLE
Use verbs for all actions

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/mnelab#295]
I think all actions should at least include a verb (we might consider Windows and macOS UX guidelines, but I'm pretty sure that's the rule). Currently, the following actions (menu entries) do *not* include verbs so we should consider renaming them:

- Edit – Channel properties...
- Edit – Annotations...
- Edit – Events...
- *Everything* in the Plot menu
- Everything in the History menu (not sure this needs verbs though)

**Comment by hofaflo** [comment]
Before I start implementing this, I'd like to discuss the wording here.

File: 
- everything has a verb, except "Settings...", but I guess this is fine?

Edit:
- Channel properties -> Edit channel properties
- Annotations -> Edit annotations
- Events -> Edit events

Plot: 
- Prefix everything with "Plot"
- Maybe use "Plot PSD" instead of "Plot power spectral density"
- slightly off-topic, but "Channel locations" could be in a category separate from "Data" and "PSD"?

Tools: 
- everything OK verb-wise
- the two NIRS entries could be moved into the root "Tools" menu

View:
- History -> Show history
  - alternatively, this could be moved to "Tools"

Help:
- the "About"s should be fine
- a link to the documentation could be added here

WDYT, @cbrnr?

**Comment by cbrnr** [comment]
Yes to everything, and if unclear specifically to these questions:

> everything has a verb, except "Settings...", but I guess this is fine?

Yes!

> Maybe use "Plot PSD" instead of "Plot power spectral density"

OK!

> slightly off-topic, but "Channel locations" could be in a category separate from "Data" and "PSD"?

Fine with me!

> the two NIRS entries could be moved into the root "Tools" menu

It is planned to add more NIRS functions in the future, but I guess we will have to create a root-level "NIRS" menu then anyway. So OK to move it into the root of "Tools" for now.

> History -> Show history

Here I'm not sure. VS Code e.g. has View–Explorer, View–Search, ... to switch to components. Our history is similar so that we could leave "History". But I also don't mind if you change it to "Show history".

> a link to the documentation could be added here

Yes, this would be helpful!

**Comment by hofaflo** [comment]
Great, thanks for the quick reply!

**Comment by cbrnr** [comment]
This has been addressed in #311.
