### ISSUE TITLE
Replace `mne.viz.center_cmap`

### ISSUE THREAD

**Issue by cbrnr** [cbrnr/mnelab#296]
We need to replace the `from mne.viz.utils import center_cmap` line because that function will be removed in the upcoming MNE-Python 1.0 release. We can use the `cnorm` parameter as shown [in the ERDS maps example](https://mne.tools/dev/auto_examples/time_frequency/time_frequency_erds.html).

**Comment by hofaflo** [comment]
With the current implementation (i.e. with center_cmap), the colorbar goes from -1 to 2, like this:
![image](https://user-images.githubusercontent.com/22592497/153947149-1581375d-4cec-4fa2-8054-49e36c192e9a.png)

Implementing this as shown in the example gives the same results as the example (surprise), which looks like this:
![image](https://mne.tools/dev/_images/sphx_glr_time_frequency_erds_002.png)

The "new" colorbar does not comply with vmin and vmax (same for the [other figure](https://mne.tools/dev/_images/sphx_glr_time_frequency_erds_001.png) in the example), is this intentional?

**Comment by cbrnr** [comment]
No, this is a bug then. It's supposed to range from -1 to 1.5 with 0 mapped to white:

```
vmin, vmax = -1, 1.5  # set min and max ERDS values in plot
cnorm = TwoSlopeNorm(vmin=vmin, vcenter=0, vmax=vmax)  # min, center & max ERDS
```

I'll try to run the example locally and see if I can reproduce.

**Comment by cbrnr** [comment]
https://github.com/mne-tools/mne-python/pull/10345

**Comment by cbrnr** [comment]
OK, so this will be in MNE 1.0. I think we can require this version in our next release. I will push a fix.

**Comment by cbrnr** [comment]
Hm. That's weird. The way this works is that the colorbar is now non-linear. This is identical to how it was previously, but it *looks* strange (never mind the differences in the maps, I didn't use exactly the same parameters).

Old:
![sphx_glr_time_frequency_erds_002](https://user-images.githubusercontent.com/4377312/154025600-7d571655-1617-455b-bdff-55cc07fd263a.png)

New:
![Figure_2](https://user-images.githubusercontent.com/4377312/154025616-6b46bcfc-99d0-4c23-869e-7a32fe7d73d4.png)

Is there a way to make the colorbar linear again?
