### ISSUE TITLE
Error in stream selection

### ISSUE THREAD

**Issue by JuliusWelzel** [cbrnr/mnelab#380]
Hi,

I noticed an unfortunate error. If the `.xdf` file has multiple streams and the `stream["info"]["stream_id"]` do not start at 0, the [selection](https://github.com/cbrnr/mnelab/blob/e0f3456e69b2429b9a4f631e15fc36e1f5e5e2d9/mnelab/io/xdf.py#L103) fetches the wrong stream based which is not based on the input-value [streams_ids](https://github.com/cbrnr/mnelab/blob/e0f3456e69b2429b9a4f631e15fc36e1f5e5e2d9/mnelab/io/xdf.py#L70).

Best,
Julius

**Comment by JuliusWelzel** [comment]
Sure, [here](https://drive.google.com/drive/folders/143Gl10O76SkE_9EkOZVmefg5OLbDjhnb?usp=sharing) you find the file and the code I used :smile:

**Comment by cbrnr** [comment]
Thanks! The problem is that you are assuming that streams are sorted by ID – this is not the case. In fact, the order is arbitrary and is set during recording by the recording setup.

You can use `pyxdf.resolve_streams()` to get an overview of all streams in the file. To match specific streams (e.g. by name), you can use `pyxdf.match_streaminfos()`.

For example:

```python
from pyxdf import match_streaminfos, resolve_streams

resolve_streams("control_joy.xdf")  # lists all streams

# get stream ID of the stream named "BrainVision RDA"
match_streaminfos(resolve_streams("control_joy.xdf"), [{"name": "BrainVision RDA"}])
# etc.
```

**Comment by JuliusWelzel** [comment]
Thanks perfect!
