### ISSUE TITLE
Allowing duplicate dataset names causes issues

### ISSUE THREAD

**Issue by bkloeckl** [cbrnr/mnelab#445]
**Issue:**
Currently, it is possible for two or more datasets to share the same name, including those generated by functions (e.g., append) that create new datasets from existing ones. This leads to complications in methods that rely on selecting specific datasets by name from the list.

**Suggested Solution:**
To prevent duplicate names, implement a check each time a new dataset is added to the list. If a duplicate name is detected, prompt the user with a renaming dialog.

**Comment by cbrnr** [comment]
I think the problem here is just the incorrect history entry, but appending data sets with identical names seems to work fine.

For example, download the following three datasets:

1. https://physionet.org/files/eegmmidb/1.0.0/S001/S001R03.edf?download
2. https://physionet.org/files/eegmmidb/1.0.0/S001/S001R04.edf?download
3. https://physionet.org/files/eegmmidb/1.0.0/S001/S001R05.edf?download

Open all three files in MNELAB (drag and drop should work), rename the last one from "S001R05" to "S001R04", and then select the first one (S001R03). Click on "Edit" – "Append data...", and the dialog shows the other two datasets both named "S001R04", which you can select and append. The result should then be the concatenation of all three datasets (which you can e.g. verify by looking at the annotations).

However, the history entry is incorrect, since `mne.concatenate_raws()` requires a list of datasets and not a list of names.

**Comment by bkloeckl** [comment]
**My suggestions:**
I would disallow duplicate names by implementing a check each time a new dataset is added to the list. This would not only enhance usability by forcing the user to give distinct and meaningful names, but also fix the issue without having to change the logic of existing functions.

For future implementations, I suggest using indices where possible, as comparing unique integer indices tends to be more reliable than comparing string names.

**Comment by cbrnr** [comment]
I agree that we should probably do both things, but I'd prefer if we also update `.append_data()` immediately to use indices (I think it's the only function right now).

Regarding the check for duplicate names, I think it should be possible to set this as a Qt validator, so that it is just not possible to enter a duplicate name. This would require no dialog.

**Comment by cbrnr** [comment]
Taking a look at how `.append_data()` is implemented, using the dataset indices might be not that straightforward, because of the `self.auto_duplicate()` call right before appending. This auto-duplication creates a copy of the current dataset after the current index in order to overwrite it with the result of the operation. This of course means that all indices that come afterwards shift by one.

**Comment by cbrnr** [comment]
Since a dataset is just a dictionary, we might also be able to add a UUID for each dataset and use that to uniquely identify it. This would be independent from both its name and its position in the `data` list.

**Comment by cbrnr** [comment]
Fixed by #449.
