### ISSUE TITLE
Montage button should probably open "Set montage" dialog if none has been selected so far

### ISSUE THREAD

**Issue by hoechenberger** [cbrnr/mnelab#64]
Currently, the button is grayed out until one sets a montage via the Edit menu. Maybe it should always be active, but present the user with the Set montage dialog box if no montage has been set.

**Comment by cbrnr** [comment]
Hm, the button plots the current montage - overloading it with two different actions might be confusing.

**Comment by hoechenberger** [comment]
You may have a valid point there…
I wonder if MNELAB, instead, could ask for a valid montage when importing a data set? Or are there any cases where users do NOT need to set a montage? (It's ALWAYS part of my workflow!)

**Comment by cbrnr** [comment]
MNELAB is just mimicking MNE's workflow here - because it is not possible to set a montage directly in a reader function, MNELAB doesn't offer this either. IMO MNELAB should make the transition to MNE as smooth as possible, so I want to avoid inventing a new workflow. (Fun fact: MNE did have some reader functions that supported setting a montage IIRC, but this was removed recently.)

**Comment by hoechenberger** [comment]
But the transition to MNE would still be smooth, as MNELAB would generate the `mne.read_*` _and_ the `set_montage()` lines, which could be viewed in the command history :)

**Comment by cbrnr** [comment]
True, but instead of bugging the user with asking if a montage should be set right after loading a file, it is probably better to not ask anything and let the user set a montage afterwards. For one, there's a keyboard shortcut (at least I hope so, and we could add global shortcuts in addition). Furthermore, many users might not want to immediately (if ever) load a montage, so they would have to click away an additional dialog.

**Comment by hoechenberger** [comment]
> Furthermore, many users might not want to immediately (if ever) load a montage

I wasn't aware of this :) So yeah, in that case, I agree with you.

Still wondering: maybe some _explanation_ as to why the Montage button is grayed out in the beginning could be helpful? Either via a tooltip? Or maybe keep the button active, but display a popup that says, "Please set a montage via `Edit / Set montage first!`"?

**Comment by cbrnr** [comment]
But the same question could be asked about the menu entry: why is the Edit - Set montage menu entry initially grayed out? I think this should be solved with some proper documentation/tutorial, which as of now totally doesn't exist at all.

**Comment by hoechenberger** [comment]
Ok I'll close this for now.
