### ISSUE TITLE
Visual programming UI

### ISSUE THREAD

**Issue by brylie** [cbrnr/mnelab#7]
Consider providing a visual programming interface for building on/offline EEG analysis flows.

# User story
> As an end user
> I would appreciate a visual programming UI
> so I can easily build pipelines for my EEG data analysis

# Goal
Allow MNE-Lab users to create EEG analysis flows by dragging, dropping, connecting, and configuring modules via a visual programming interface.

# Examples
## PyQtGraph

[PyQtGraph](http://www.pyqtgraph.org/) has modules to allow [visual programming with flowcharts](http://www.pyqtgraph.org/documentation/flowchart/) (and is used in the, somewhat related, [ACQ4 Neurophysiology Acquisition and Analysis System](http://acq4.org/screenshots.html):

![PyQtGraph example application](http://www.pyqtgraph.org/images/flowchart.png)

## OpenViBE Designer
OpenViBE Designer offers a visual programming environment for creating EEG analysis pipelines:

![OpenViBE screenshot](http://openvibe.inria.fr/openvibe/wp-content/uploads/2011/05/screenshot-designer.png)

## Orange
Another relevant tool is [Orange](https://orange.biolab.si/):

> Open source machine learning and data visualization for novice and expert. Interactive data analysis workflows with a large toolbox.

![Orange screenshot](https://orange.biolab.si/static/homepage/screenshots/images/rank.png)

**Comment by chrismullins** [comment]
+1

I was thinking about using pyqtgraph for some of the data interaction as well, so maybe it can be further integrated for this sort of thing once we have more in the way of pipeline steps.

**Comment by brylie** [comment]
I would like to help. Are there any small tasks I may take to 'wade into the water'? I am coming from a JavaScript background, but am transitioning more to Python/Django and perhaps PyQt.

**Comment by brylie** [comment]
I added also the Orange Machine Learning toolbox. It has a visual programming interface and is written with Python and Qt 5. It may be possible to extend Orange with some EEG analysis related tools, without the need to build a bespoke UI framework for MNE-Lab.

**Comment by cbrnr** [comment]
A visual programming UI to generate pipelines would certainly be a nice feature. There is also a Python-based product called [Neuropype](https://www.neuropype.io/), but unfortunately this is commercial and not open source.

However, I feel that at the moment this is not where I would like to go with MNELAB. I'd like to start with something similar to EEGLAB just to make the transition to MNELAB as smooth as possible. I'm also not a big fan of visual programming envs (think Simulink or LabView), because scripts are much simpler and serve the same purpose. With MNELAB, you can perform analyses with the GUI, but each step gets recorded in a history that can be put into a script. I think this is sufficient for now.

It would be cool if MNE added support for pipelines (à la scikit-learn) before we think about creating a visual UI for that. But again, I'm not even sure if MNE really needs pipelines in the first place. In any case, it might be worth bringing this issue up in the MNE repo.

**Comment by brylie** [comment]
Woah, Neuropype may be using Orange3. If so, they might be in violation of the GPL.

**Comment by cbrnr** [comment]
Hm, they say that NeuroPype Community Edition is 100% free with source code for non-commercial use. Maybe they will release it under the GPL (they'd better if they're using a GPL'd tool)? Anyway, since there is nothing available right now it's hard to tell, but if this is going to be released it will definitely be interesting.

**Comment by brylie** [comment]
Ah, that is one thing that irks me somewhat, when people say the GPL doesn't allow commercial use. Or, perhaps they want to add non-commercial restrictions to GPL software, which would violate GPL.

**Comment by cbrnr** [comment]
You're right, they can't say that a GPL'd software can only be used non-commercially. You could drop them a friendly email and ask about their plans.

**Comment by brylie** [comment]
Cool beans, thanks for the suggestion.

Also, please consider expanding on my [initial inquiry with the Orange3 community](https://github.com/biolab/orange3/issues/2532). I want to get a feel for what is involved with getting Orange3 to support on- and off-line analysis for EEG data :-)

**Comment by cbrnr** [comment]
Closing since this is out of scope and should be solved elsewhere.
